version: '3'
services:
  # Spring Boot application
  spring-app:
    image: dabbechmondher/devopsspring:latest  # Use the existing image from Docker Hub
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
    depends_on:
      - mysql

  # MySQL database
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: spring_db
    ports:
      - "3306:3306"
    volumes:
      - /path/to/mysql-data:/var/lib/mysql
